export const authContants = {
  AUTHENTICATE: 'AUTHENTICATE',
  AUTH_START: 'AUTH_START',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_CLEAR: 'AUTH_CLEAR',

  AUTH_TIMEOUT: 'AUTH_TIMEOUT'
}