export const signupConstants = {
  SIGN_UP_INITIATION_SUCCESS: 'SIGN_UP_INITIATION_SUCCESS',
  SIGN_UP_INITIATION_FAIL: 'SIGN_UP_INITIATION_FAIL',

  SIGN_UP_VALIDATION_SUCCESS: 'SIGN_UP_VALIDATION_SUCCESS',
  SIGN_UP_VALIDATION_FAIL: 'SIGN_UP_VALIDATION_FAIL',

  SIGN_UP_REVALIDATION_SUCCESS: 'SIGN_UP_REVALIDATION_SUCCESS',
  SIGN_UP_REVALIDATION_FAIL: 'SIGN_UP_REVALIDATION_FAIL',

  SIGN_UP_COMPLETION_SUCCESS: 'SIGN_UP_COMPLETION_SUCCESS',
  SIGN_UP_COMPLETION_FAIL: 'SIGN_UP_COMPLETION_FAIL',


  SIGN_UP_RESET: 'SIGN_UP_RESET',
  SIGN_UP_RESET_ERRORS: 'SIGN_UP_RESET_ERRORS'
}