export const armConstants = {
    GET_ARM_REQUESTING: 'GET_ARM_REQUESTING',
    GET_ARM_SUCCESS: 'GET_ARM_SUCCESS',
    GET_ARM_FAIL: 'GET_ARM_FAIL',

    ADD_ARM_REQUESTING: 'ADD_ARM_REQUESTING',
    ADD_ARM_SUCCESS: 'ADD_ARM_SUCCESS',
    ADD_ARM_FAIL: 'ADD_ARM_FAIL',

    EDIT_ARM_REQUESTING: 'EDIT_ARM_REQUESTING',
    EDIT_ARM_SUCCESS: 'EDIT_ARM_SUCCESS',
    EDIT_ARM_FAIL: 'EDIT_ARM_FAIL',

    DELETE_ARM_REQUESTING: 'DELETE_ARM_REQUESTING',
    DELETE_ARM_SUCCESS: 'DELETE_ARM_SUCCESS',
    DELETE_ARM_FAIL: 'DELETE_ARM_FAIL',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}