export const classContants = {
  GET_CLASS_REQUESTING: "GET_CLASS_REQUESTING",
  GET_CLASS_SUCCESS: "GET_CLASS_SUCCESS",
  GET_CLASS_FAIL: "GET_CLASS_FAIL",

  ADD_CLASS_REQUESTING: "ADD_CLASS_REQUESTING",
  ADD_CLASS_SUCCESS: "ADD_CLASS_SUCCESS",
  ADD_CLASS_FAIL: "ADD_CLASS_FAIL",

  EDIT_CLASS_REQUESTING: "EDIT_CLASS_REQUESTING",
  EDIT_CLASS_SUCCESS: "EDIT_CLASS_SUCCESS",
  EDIT_CLASS_FAIL: "EDIT_CLASS_FAIL",

  DELETE_CLASS_REQUESTING: "DELETE_CLASS_REQUESTING",
  DELETE_CLASS_SUCCESS: "DELETE_CLASS_SUCCESS",
  DELETE_CLASS_FAIL: "DELETE_CLASS_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
