export const classArmConstants = {
    GET_CLASSARM_REQUESTING: 'GET_CLASSARM_REQUESTING',
    GET_CLASSARM_SUCCESS: 'GET_CLASSARM_SUCCESS',
    GET_CLASSARM_FAIL: 'GET_CLASSARM_FAIL',

    ADD_CLASSARM_REQUESTING: 'ADD_CLASSARM_REQUESTING',
    ADD_CLASSARM_SUCCESS: 'ADD_CLASSARM_SUCCESS',
    ADD_CLASSARM_FAIL: 'ADD_CLASSARM_FAIL',

    EDIT_CLASSARM_REQUESTING: 'EDIT_CLASSARM_REQUESTING',
    EDIT_CLASSARM_SUCCESS: 'EDIT_CLASSARM_SUCCESS',
    EDIT_CLASSARM_FAIL: 'EDIT_CLASSARM_FAIL',

    DELETE_CLASSARM_REQUESTING: 'DELETE_CLASSARM_REQUESTING',
    DELETE_CLASSARM_SUCCESS: 'DELETE_CLASSARM_SUCCESS',
    DELETE_CLASSARM_FAIL: 'DELETE_CLASSARM_FAIL',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}