export const classRoomConstants = {
    GET_CLASSROOM_REQUESTING: 'GET_CLASSROOM_REQUESTING',
    GET_CLASSROOM_SUCCESS: 'GET_CLASSROOM_SUCCESS',
    GET_CLASSROOM_FAIL: 'GET_CLASSROOM_FAIL',

    GET_A_CLASSROOM_REQUESTING: 'GET_A_CLASSROOM_REQUESTING',
    GET_A_CLASSROOM_SUCCESS: 'GET_A_CLASSROOM_SUCCESS',
    GET_A_CLASSROOM_FAIL: 'GET_A_CLASSROOM_FAIL',

    ADD_CLASSROOM_REQUESTING: 'ADD_CLASSROOM_REQUESTING',
    ADD_CLASSROOM_SUCCESS: 'ADD_CLASSROOM_SUCCESS',
    ADD_CLASSROOM_FAIL: 'ADD_CLASSROOM_FAIL',

    EDIT_CLASSROOM_REQUESTING: 'EDIT_CLASSROOM_REQUESTING',
    EDIT_CLASSROOM_SUCCESS: 'EDIT_CLASSROOM_SUCCESS',
    EDIT_CLASSROOM_FAIL: 'EDIT_CLASSROOM_FAIL',

    DELETE_CLASSROOM_REQUESTING: 'DELETE_CLASSROOM_REQUESTING',
    DELETE_CLASSROOM_SUCCESS: 'DELETE_CLASSROOM_SUCCESS',
    DELETE_CLASSROOM_FAIL: 'DELETE_CLASSROOM_FAIL',


    CLEAR_ERRORS: 'CLEAR_ERRORS'
}