export const houseContants = {
  GET_HOUSE_REQUESTING: "GET_HOUSE_REQUESTING",
  GET_HOUSE_SUCCESS: "GET_HOUSE_SUCCESS",
  GET_HOUSE_FAIL: "GET_HOUSE_FAIL",

  ADD_HOUSE_REQUESTING: "ADD_HOUSE_REQUESTING",
  ADD_HOUSE_SUCCESS: "ADD_HOUSE_SUCCESS",
  ADD_HOUSE_FAIL: "ADD_HOUSE_FAIL",

  EDIT_HOUSE_REQUESTING: "EDIT_HOUSE_REQUESTING",
  EDIT_HOUSE_SUCCESS: "EDIT_HOUSE_SUCCESS",
  EDIT_HOUSE_FAIL: "EDIT_HOUSE_FAIL",

  DELETE_HOUSE_REQUESTING: "DELETE_HOUSE_REQUESTING",
  DELETE_HOUSE_SUCCESS: "DELETE_HOUSE_SUCCESS",
  DELETE_HOUSE_FAIL: "DELETE_HOUSE_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
