export const schoolDetailsConstants = {
  SCHOOL_DETAILS_REQUESTING: 'SCHOOL_DETAILS_REQUESTING',
  SCHOOL_DETAILS_SUCCESS: 'SCHOOL_DETAILS_SUCCESS',
  SCHOOL_DETAILS_FAIL: 'SCHOOL_DETAILS_FAIL',

  EDIT_SCHOOL_DETAILS_REQUESTING: 'EDIT_SCHOOL_DETAILS_REQUESTING',
  EDIT_SCHOOL_DETAILS_SUCCESS: 'EDIT_SCHOOL_DETAILS_SUCCESS',
  EDIT_SCHOOL_DETAILS_FAIL: 'EDIT_SCHOOL_DETAILS_FAIL',

  CLEAR_ERRORS: 'CLEAR_ERRORS'
}