export const sectionContants = {
  GET_SECTION_REQUESTING: "GET_SECTION_REQUESTING",
  GET_SECTION_SUCCESS: "GET_SECTION_SUCCESS",
  GET_SECTION_FAIL: "GET_SECTION_FAIL",

  ADD_SECTION_REQUESTING: "ADD_SECTION_REQUESTING",
  ADD_SECTION_SUCCESS: "ADD_SECTION_SUCCESS",
  ADD_SECTION_FAIL: "ADD_SECTION_FAIL",

  EDIT_SECTION_REQUESTING: "EDIT_SECTION_REQUESTING",
  EDIT_SECTION_SUCCESS: "EDIT_SECTION_SUCCESS",
  EDIT_SECTION_FAIL: "EDIT_SECTION_FAIL",

  DELETE_SECTION_REQUESTING: "DELETE_SECTION_REQUESTING",
  DELETE_SECTION_SUCCESS: "DELETE_SECTION_SUCCESS",
  DELETE_SECTION_FAIL: "DELETE_SECTION_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
