export const sessionConstants = {
    GET_SESSION_REQUESTING: 'GET_SESSION_REQUESTING',
    GET_SESSION_SUCCESS: 'GET_SESSION_SUCCESS',
    GET_SESSION_FAIL: 'GET_SESSION_FAIL',

    ADD_SESSION_REQUESTING: 'ADD_SESSION_REQUESTING',
    ADD_SESSION_SUCCESS: 'ADD_SESSION_SUCCESS',
    ADD_SESSION_FAIL: 'ADD_SESSION_FAIL',

    EDIT_SESSION_REQUESTING: 'EDIT_SESSION_REQUESTING',
    EDIT_SESSION_SUCCESS: 'EDIT_SESSION_SUCCESS',
    EDIT_SESSION_FAIL: 'EDIT_SESSION_FAIL',

    DELETE_SESSION_REQUESTING: 'DELETE_SESSION_REQUESTING',
    DELETE_SESSION_SUCCESS: 'DELETE_SESSION_SUCCESS',
    DELETE_SESSION_FAIL: 'DELETE_SESSION_FAIL',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}