export const subjectContants = {
  GET_SUBJECT_REQUESTING: 'GET_SUBJECT_REQUESTING',
  GET_SUBJECT_SUCCESS: 'GET_SUBJECT_SUCCESS',
  GET_SUBJECT_FAIL: 'GET_SUBJECT_FAIL',

  ADD_SUBJECT_REQUESTING: 'ADD_SUBJECT_REQUESTING',
  ADD_SUBJECT_SUCCESS: 'ADD_SUBJECT_SUCCESS',
  ADD_SUBJECT_FAIL: 'ADD_SUBJECT_FAIL',

  EDIT_SUBJECT_REQUESTING: 'EDIT_SUBJECT_REQUESTING',
  EDIT_SUBJECT_SUCCESS: 'EDIT_SUBJECT_SUCCESS',
  EDIT_SUBJECT_FAIL: 'EDIT_SUBJECT_FAIL',

  DELETE_SUBJECT_REQUESTING: 'DELETE_SUBJECT_REQUESTING',
  DELETE_SUBJECT_SUCCESS: 'DELETE_SUBJECT_SUCCESS',
  DELETE_SUBJECT_FAIL: 'DELETE_SUBJECT_FAIL',

  CLEAR_SUBJECT_ERRORS: 'CLEAR_SUBJECT_ERRORS'
}