export const termConstants = {
    GET_TERMS_REQUESTING: 'GET_TERMS_REQUESTING',
    GET_TERMS_SUCCESS: 'GET_TERMS_SUCCESS',
    GET_TERMS_FAIL: 'GET_TERMS_FAIL',

    ADD_TERMS_REQUESTING: 'ADD_TERMS_REQUESTING',
    ADD_TERMS_SUCCESS: 'ADD_TERMS_SUCCESS',
    ADD_TERMS_FAIL: 'ADD_TERMS_FAIL',

    EDIT_TERMS_REQUESTING: 'EDIT_TERMS_REQUESTING',
    EDIT_TERMS_SUCCESS: 'EDIT_TERMS_SUCCESS',
    EDIT_TERMS_FAIL: 'EDIT_TERMS_FAIL',

    DELETE_TERMS_REQUESTING: 'DELETE_TERMS_REQUESTING',
    DELETE_TERMS_SUCCESS: 'DELETE_TERMS_SUCCESS',
    DELETE_TERMS_FAIL: 'DELETE_TERMS_FAIL',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}