export const studentContants = {
  GET_STUDENTS_REQUESTING: 'GET_STUDENTS_REQUESTING',
  GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
  GET_STUDENTS_FAIL: 'GET_STUDENTS_FAIL',

  GET_CERTIFICATES_REQUESTING: 'GET_CERTIFICATES_REQUESTING',
  GET_CERTIFICATES_SUCCESS: 'GET_CERTIFICATES_SUCCESS',
  GET_CERTIFICATES_FAIL: 'GET_CERTIFICATES_FAIL',

  GET_STUDENT_REQUESTING: 'GET_STUDENT_REQUESTING',
  GET_STUDENT_SUCCESS: 'GET_STUDENT_SUCCESS',
  GET_STUDENT_FAIL: 'GET_STUDENT_FAIL',

  ADD_STUDENT_REQUESTING: 'ADD_STUDENT_REQUESTING',
  ADD_STUDENT_SUCCESS: 'ADD_STUDENT_SUCCESS',
  ADD_STUDENT_FAIL: 'ADD_STUDENT_FAIL',

  ADD_CERTIFICATE_REQUESTING: 'ADD_CERTIFICATE_REQUESTING',
  ADD_CERTIFICATE_SUCCESS: 'ADD_CERTIFICATE_SUCCESS',
  ADD_CERTIFICATE_FAIL: 'ADD_CERTIFICATE_FAIL',


}