export const adminDashboardConstants = {
  GET_ADMIN_DASHBOARD_REQUESTING: 'GET_ADMIN_DASHBOARD_REQUESTING',
  GET_ADMIN_DASHBOARD_SUCCESS: 'GET_ADMIN_DASHBOARD_SUCCESS',
  GET_ADMIN_DASHBOARD_FAIL: 'GET_ADMIN_DASHBOARD_FAIL'
}