export const employeeDashboardConstants = {
    GET_EMPLOYEE_DASHBOARD_REQUESTING: 'GET_EMPLOYEE_DASHBOARD_REQUESTING',
    GET_EMPLOYEE_DASHBOARD_SUCCESS: 'GET_EMPLOYEE_DASHBOARD_SUCCESS',
    GET_EMPLOYEE_DASHBOARD_FAIL: 'GET_EMPLOYEE_DASHBOARD_FAIL'
}