export const guardianDashboardConstants = {
  GET_TOTAL_FEES_REQUESTING: "GET_TOTAL_FEES_REQUESTING",
  GET_TOTAL_FEES_SUCCESS: "GET_TOTAL_FEES_SUCCESS",
  GET_TOTAL_FEES_FAIL: "GET_TOTAL_FEES_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
