export const studentDashboardConstants = {
    GET_STUDENT_DASHBOARD_REQUESTING: 'GET_STUDENT_DASHBOARD_REQUESTING',
    GET_STUDENT_DASHBOARD_SUCCESS: 'GET_STUDENT_DASHBOARD_SUCCESS',
    GET_STUDENT_DASHBOARD_FAIL: 'GET_STUDENT_DASHBOARD_FAIL',

    CLEAR_ERRORS: "CLEAR_ERRORS",
};
